[package]
name = "cow-amm-poller"
version = "0.1.0"
edition = "2021"
description = "Using the ConstantProductHelper to poll amms"

[dependencies]
cow-amm-common.workspace = true
alloy.workspace = true
eyre.workspace = true
futures.workspace = true
tokio.workspace = true
